/**
 * Export utilities for Comments Insight
 */
import { HistoryItem, Comment } from '../types';

/**
 * Export comments as CSV
 * @param comments - Comments to export
 * @param filename - Output filename
 */
export function exportCommentsAsCSV(comments: Comment[], filename?: string): void {
  const headers = ['Username', 'Timestamp', 'Likes', 'Content', 'Replies Count'];
  const rows = comments.map(comment => [
    `"${comment.username.replace(/"/g, '""')}"`,
    `"${comment.timestamp}"`,
    comment.likes.toString(),
    `"${comment.content.replace(/"/g, '""')}"`,
    comment.replies.length.toString()
  ]);
  
  const csv = [headers.join(','), ...rows.map(row => row.join(','))].join('\n');
  downloadFile(csv, filename || `comments-${Date.now()}.csv`, 'text/csv');
}

/**
 * Export analysis as Markdown
 * @param item - History item with analysis
 * @param filename - Output filename
 */
export function exportAnalysisAsMarkdown(item: HistoryItem, filename?: string): void {
  if (!item.analysis) {
    throw new Error('No analysis available for this item');
  }

  const markdown = `# Comment Analysis Report

## Post Information
- **Title**: ${item.title}
- **Platform**: ${item.platform}
- **URL**: ${item.url}
- **Extracted**: ${new Date(item.extractedAt).toLocaleString()}
- **Total Comments**: ${item.commentsCount}

## Analysis Results

${item.analysis.markdown}

---

*Report generated by Comments Insight*
*Analysis Date: ${new Date(item.analysis.generatedAt).toLocaleString()}*
*Tokens Used: ${item.analysis.tokensUsed}*
`;

  downloadFile(markdown, filename || `analysis-${Date.now()}.md`, 'text/markdown');
}

/**
 * Export complete data (comments + analysis) as JSON
 * @param item - History item
 * @param filename - Output filename
 */
export function exportCompleteData(item: HistoryItem, filename?: string): void {
  const data = {
    metadata: {
      title: item.title,
      platform: item.platform,
      url: item.url,
      extractedAt: item.extractedAt,
      analyzedAt: item.analyzedAt,
      commentsCount: item.commentsCount,
      exportDate: Date.now(),
    },
    comments: item.comments,
    analysis: item.analysis,
  };
  
  const json = JSON.stringify(data, null, 2);
  downloadFile(json, filename || `complete-data-${Date.now()}.json`, 'application/json');
}

/**
 * Download file helper
 * @param content - File content
 * @param filename - Filename
 * @param mimeType - MIME type
 */
function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
